---
title: "Day 5 interactive"
format: html
editor: visual
---

```{r}
library(testthat)
```

# Function Testing 

## Step 1: Create Function 

```{r}
mean_range <- function(df) {
  col_means <- apply(X = df,
                     MARGIN = 2,               # calculate by column
                     FUN = mean, na.rm = TRUE) # apply function mean
  col_mean_max <- max(col_means)
  col_mean_min <- min(col_means)
  return(c(col_mean_min, col_mean_max))        # will return both 
}
```

```{r}
# testing function created above on df = mtcars
mean_range(mtcars)
```

## Step 2: Testing function 

- return a vector of length 2

- always be numeric 

```{r}
expect_length(mean_range(mtcars), 2)

expect_type(mean_range(mtcars), "double")

expect_true(mean_range(mtcars)[1] <= mean_range(mtcars)[1])
```


## Sourcing code

```{r}
source(here::here("src", "name_cart.R"))
```

```{r}
name_cart("paella", "chinchilla")
```

### Sourcing Cork Oak function

```{r}
source(here::here("src", "cork_oak_growth.R"))
```

```{r}
height_t2(50, 2, 5)
```

